app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::resource('/', 'Web\User\BerandaController');
Route::resource('/lulus', 'Web\User\InfoController');
Route::resource('/ceklulus', 'Web\User\InfoController@create');
Route::resource('/alumni', 'Web\User\AlumniController');
Route::resource('/tambah_alumni', 'Web\User\AlumniController@create');
Route::resource('/kontak', 'Web\User\KontakController');

Route::auth();

//ADMIN
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/infolulus', 'Web\Admin\SiswaController');
Route::resource('/admin/alumni', 'Web\Admin\AlumniController');
Route::resource('/admin/kontak', 'Web\Admin\KontakController');
Route::resource('/admin/aktifasi', 'Web\Admin\InfoController');

app/Kontak.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kontak extends Model
{
    protected $table = 'kontaks';

    protected $fillable = [
        'meta_key','meta_value'
    ];
}

app/Http/Controllers/Web/Admin/KontakController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Kontak;

class KontakController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $kontak = Kontak::get()->all();
        return view('admin.kontak.kontak',compact('kontak'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $kontak = $request->all();
        Kontak::create($kontak);

        $notification = array(
            'message' => 'Data Kontak berhasil ditambah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.kontak.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $kontak = Kontak::findOrFail($id);

        return view('admin.kontak.edit_kontak', compact('kontak'));
    }

    public function update(Request $request, $id)
    {
        $kontak = Kontak::findOrFail($id);

        $kontak->update($request->all());
        $notification = array(
            'message' => 'Data Kontak berhasil diubah.',
            'alert-type' => 'success'
        );
        return redirect()->route('admin.kontak.index')->with($notification);
    }

    public function destroy($id)
    {
        $kontak = Kontak::findOrFail($id);
        $notification = array(
            'message' => 'Data Kontak berhasil dihapus.',
            'alert-type' => 'error'
        );
        Kontak::find($id)->delete();
        return redirect()->route('admin.kontak.index')->with($notification);
    }
}

app/Http/Controllers/Web/User/KontakController.php
<?php

namespace App\Http\Controllers\Web\User;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Kontak;
class KontakController extends Controller
{
    public function index()
    {
        $kontak = Kontak::get()->all();
        return view('user.kontak.kontak',compact('kontak'));
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/kontak/edit_kontak.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Kontak
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Kontak</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($kontak, ['route' => ['admin.kontak.update', $kontak],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_kontak_edit', ['model' => $kontak])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/kontak/kontak.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Kontak
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Kontak</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.kontak.store', 'class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_kontak_tambah')
                        {!! Form::close() !!}
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Daftar</th>
                                <th>Isi</th>
                                <th colspan="2" align="center">Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($kontak as $item)
                                <tr>
                                    <td>{{ $item->meta_key }}</td>
                                    <td>{{ $item->meta_value }}</td>
                                    <td>
                                      <div class="col-md-12">
                                          <div class="col-md-6">
                                              <a href="{{ route('admin.kontak.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                          </div>
                                          <div class="col-md-6">
                                              {{ Form::open(['route' => ['admin.kontak.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                  {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                              {{ Form::close() }}
                                          </div>
                                      </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection