app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::resource('/', 'Web\User\BerandaController');
Route::resource('/lulus', 'Web\User\InfoController');
Route::resource('/ceklulus', 'Web\User\InfoController@create');
Route::resource('/alumni', 'Web\User\AlumniController');
Route::resource('/tambah_alumni', 'Web\User\AlumniController@create');
Route::resource('/kontak', 'Web\User\KontakController');

Route::auth();

//ADMIN
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/infolulus', 'Web\Admin\SiswaController');
Route::resource('/admin/alumni', 'Web\Admin\AlumniController');
Route::resource('/admin/kontak', 'Web\Admin\KontakController');
Route::resource('/admin/aktifasi', 'Web\Admin\InfoController');

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $table = 'siswas';
    protected $fillable = ['nama','no_ujian','info','nilai'];
}

app/Http/Controllers/Web/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\SiswaRequest;
use App\Http\Controllers\Controller;

use App\Siswa;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $no = 1;

        $siswa = Siswa::orderBy('nama','asc')->get()->all();

        return view('admin.siswa.siswa', compact('siswa','no'));
    }

    public function create()
    {
        return view('admin.siswa.tambah_siswa');
    }

    public function store(SiswaRequest $request)
    {
        // SIMPAN DATA SISWA META
        $siswa = $request->only('nama','no_ujian','nilai');
        $siswa['info'] = 'Lulus';

        Siswa::create($siswa);

        $notification = array(
            'message' => 'Siswa berhasil ditambah.',
            'alert-type' => 'success'
        );
        return redirect()->route('admin.infolulus.create')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $siswa = Siswa::findOrFail($id);

        return view('admin.siswa.edit_siswa', compact('siswa'));
    }

    public function update(SiswaRequest $request, $id)
    {
        $siswa = Siswa::findOrFail($id);

        $siswa->update($request->all());
        $notification = array(
            'message' => 'Data Siswa berhasil diubah.',
            'alert-type' => 'success'
        );
        return redirect()->route('admin.infolulus.index')->with($notification);
    }

    public function destroy($id)
    {
        $siswa = Siswa::findOrFail($id);
        $notification = array(
            'message' => 'Data Siswa berhasil dihapus.',
            'alert-type' => 'error'
        );
        Siswa::find($id)->delete();
        return redirect()->route('admin.infolulus.index')->with($notification);
    }
}

resources/views/admin/siswa/edit_siswa.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data Siswa</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($siswa, ['route' => ['admin.infolulus.update', $siswa],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_siswa_edit', ['model' => $siswa])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/siswa/siswa.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">


                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Hapus Semuda Data Siswa</h3>
                    </div>

                    <div class="box-body" style="overflow-x:auto;">
                        {{ Form::open(['route' => ['admin.aktifasi.destroy' , '1'] ,'method' => 'DELETE']) }}
                            {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                        {{ Form::close() }}
                    </div>
                </div>

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data Siswa</h3>
                    </div>
                    <div class="box-body" style="overflow-x:auto;">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nomor Ujian</th>
                                    <th>Nama</th>
                                    <th>Nilai</th>
                                    <th>Info</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($siswa as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->no_ujian }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->nilai }}</td>
                                        <td>{{ $item->info }}</td>
                                        <td><a href="{{ route('admin.infolulus.edit', $item->id) }}" class="btn btn-primary">Ubah</a></td>
                                        <td>
                                            {{ Form::open(['route' => ['admin.infolulus.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/siswa/tambah_siswa.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-8">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Siswa</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.infolulus.store', 'class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_siswa_tambah')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection