app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::resource('/', 'Web\User\BerandaController');
Route::resource('/lulus', 'Web\User\InfoController');
Route::resource('/ceklulus', 'Web\User\InfoController@create');
Route::resource('/alumni', 'Web\User\AlumniController');
Route::resource('/tambah_alumni', 'Web\User\AlumniController@create');
Route::resource('/kontak', 'Web\User\KontakController');

Route::auth();

//ADMIN
Route::resource('/admin/beranda', 'Web\Admin\BerandaController');
Route::resource('/admin/infolulus', 'Web\Admin\SiswaController');
Route::resource('/admin/alumni', 'Web\Admin\AlumniController');
Route::resource('/admin/kontak', 'Web\Admin\KontakController');
Route::resource('/admin/aktifasi', 'Web\Admin\InfoController');

app/Alumni.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alumni extends Model
{
    protected $table = 'alumnis';
    protected $with = ['jurusan'];
    protected $fillable = [
        'status_id','jurusan_id','nama','jk','tanggal_lahir',
        'tahun_lulus','bekerja_kuliah','alamat_kantor_kampus','alamat','email','telp'
    ];

    // relasi ke jurusan
    public function jurusan()
    {
        return $this->belongsTo('App\Jurusan', 'jurusan_id');
    }

    // relasi ke status
    public function status()
    {
        return $this->belongsTo('App\Status', 'status_id');
    }

}

app/Http/Controllers/Web/Admin/AlumniController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Jurusan;
use App\Status;
use App\Alumni;

class AlumniController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index(Request $request)
    {
        $q = $request->get('q');

        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 10 - 9;
        }else{
            $no=1;
        }
        
        $alumni = Alumni::get()->all();

        return view('admin.alumni.alumni', compact('alumni','no'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $tahun = date('Y');
        $jurusan = Jurusan::lists('jurusan', 'id');
        $status = Status::lists('status', 'id');

        $alumni = Alumni::findOrFail($id);

        return view('admin.alumni.edit_alumni', compact('alumni','tahun','jurusan','status'));
    }

    public function update(Request $request, $id)
    {
        $alumni = Alumni::findOrFail($id);

        $alumni->update($request->all());
        $notification = array(
            'message' => 'Data Alumni dengan nama '.$alumni->nama.' berhasil diubah.',
            'alert-type' => 'success'
        );
        return redirect()->route('admin.alumni.index')->with($notification);
    }

    public function destroy($id)
    {
        $alumni = Alumni::findOrFail($id);
        $notification = array(
            'message' => 'Data Alumni dengan nama '.$alumni->nama.' berhasil dihapus.',
            'alert-type' => 'error'
        );
        Alumni::find($id)->delete();

        return redirect()->route('admin.alumni.index')->with($notification);
    }
}

app/Http/Controllers/Web/User/AlumniController.php
<?php

namespace App\Http\Controllers\Web\User;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\AlumniUserRequest;;
use App\Http\Controllers\Controller;

use App\Jurusan;
use App\Status;
use App\Alumni;

class AlumniController extends Controller
{

    public function index()
    {
        $alumni = Alumni::orderBy('id','desc')->get()->all();

        return view('user.alumni.alumni', compact('alumni'));
    }

    public function create()
    {
        $tahun = date('Y');
        $jurusan = Jurusan::lists('jurusan', 'id');
        $status = Status::lists('status', 'id');

        return view('user.alumni.tambahdata', compact('jurusan','status','tahun'));
    }


    public function store(AlumniUserRequest $request)
    {
        Alumni::create($request->all());
        
        $notification = array(
            'message' => 'Data Alumni dengan nama '.$request->nama.' telah berhasil ditambah.',
            'alert-type' => 'success'
        );

        return redirect()->route('alumni.index')->with($notification);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/alumni/alumni.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Alumni
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title">Data Alumni</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="overflow-x:auto;">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>JK</th>
                            <th>Tanggal Lahir</th>
                            <th>Alamat</th>
                            <th>Tahun Lulus</th>
                            <th>Jurusan</th>
                            <th>Status</th>
                            <th>Bekerja / Kuliah</th>
                            <th>Email / Telp</th>
                            <th>Ubah</th>
                            <th>Hapus</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($alumni as $item)
                            <tr>
                                <td>{{ $item->nama }}</td>
                                <td>{{ $item->jk }}</td>
                                <td>{{ $item->tanggal_lahir }}</td>
                                <td>{{ $item->alamat }}</td>
                                <td>{{ $item->tahun_lulus }}</td>
                                <td>{{ $item->jurusan->jurusan }}</td>
                                <td>{{ $item->status->status }}</td>
                                <td>
                                    {{ $item->bekerja_kuliah }}<br><br>
                                    Alamat : {{ $item->alamat_kantor_kampus }}
                                </td>
                                <td>{{ $item->email }}<br>{{ $item->telp }}</td>
                                <td><a href="{{ route('admin.alumni.edit', $item->id) }}" class="btn btn-primary">Ubah</a></td>
                                <td>
                                    {{ Form::open(['route' => ['admin.alumni.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                        {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
          </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/alumni/edit_alumni.blade.php
@extends('layouts.admin')

@section('content')

    <section class="content-header">
        <h1>
            Alumni
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data Alumni</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($alumni, ['route' => ['admin.alumni.update', $alumni],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_alumni_edit', ['model' => $alumni])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection